spring:
    application:
        name: helloService-consumer

    # 可以不用配置，默认按本地8848端口连接
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 127.0.0.1:8849
#            username: nacos
#            password: nacos